from .courses.models import *
from .groups.models import *
from .news.models import *
from .products.models import *
from .students.models import *
from .teachers.models import *
from .users.models import *
from .events.models import *
from .points_history.models import *
