"""init tables

Revision ID: 5b190f38ffca
Revises: 
Create Date: 2025-06-16 22:25:46.278966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b190f38ffca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('age_category', sa.Enum('ALL', 'SIX_PLUS', 'TWELVE_PLUS', name='agecategory'), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('author_name', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price IS NULL OR price >= 0', name=op.f('courses_positive_price_check_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('courses_pkey')),
    sa.UniqueConstraint('name', name=op.f('courses_name_key'))
    )
    op.create_table('file_homeworks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('file_homeworks_pkey'))
    )
    op.create_table('lesson_html_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('lesson_html_files_pkey'))
    )
    op.create_table('news',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('news_pkey'))
    )
    op.create_index(op.f('news_name_idx'), 'news', ['name'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price IS NULL OR price >= 0', name=op.f('products_positive_price_check_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('products_pkey'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('patronymic', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('STUDENT', 'TEACHER', 'ADMIN', 'SUPERADMIN', name='userrole'), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('username', name=op.f('users_username_key'))
    )
    op.create_index(op.f('users_email_idx'), 'users', ['email'], unique=False)
    op.create_index(op.f('users_phone_number_idx'), 'users', ['phone_number'], unique=False)
    op.create_table('homeworks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file_homeworks.id'], name=op.f('homeworks_file_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('homeworks_pkey'))
    )
    op.create_table('lessons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('teacher_material_id', sa.UUID(), nullable=True),
    sa.Column('student_material_id', sa.UUID(), nullable=True),
    sa.Column('homework_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('lessons_course_id_fkey')),
    sa.ForeignKeyConstraint(['homework_id'], ['lesson_html_files.id'], name=op.f('lessons_homework_id_fkey')),
    sa.ForeignKeyConstraint(['student_material_id'], ['lesson_html_files.id'], name=op.f('lessons_student_material_id_fkey')),
    sa.ForeignKeyConstraint(['teacher_material_id'], ['lesson_html_files.id'], name=op.f('lessons_teacher_material_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('lessons_pkey'))
    )
    op.create_table('notification_recipients',
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('recipient_type', sa.String(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("recipient_type IN ('student', 'group')", name=op.f('notification_recipients_check_recipient_type_check')),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], name=op.f('notification_recipients_notification_id_fkey')),
    sa.PrimaryKeyConstraint('notification_id', 'recipient_id', 'id', name=op.f('notification_recipients_pkey'))
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('password_reset_tokens_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('password_reset_tokens_pkey'))
    )
    op.create_table('photo_courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('photo_courses_course_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('photo_courses_pkey')),
    sa.UniqueConstraint('course_id', name=op.f('photo_courses_course_id_key'))
    )
    op.create_table('photo_news',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('news_id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], name=op.f('photo_news_news_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('photo_news_pkey'))
    )
    op.create_table('photo_products',
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('photo_products_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('photo_products_pkey')),
    sa.UniqueConstraint('product_id', name=op.f('photo_products_product_id_key'))
    )
    op.create_table('read_status',
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], name=op.f('read_status_notification_id_fkey')),
    sa.PrimaryKeyConstraint('notification_id', 'student_id', 'id', name=op.f('read_status_pkey'))
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('hashed_refresh_token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('refresh_tokens_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('refresh_tokens_pkey'))
    )
    op.create_index(op.f('refresh_tokens_hashed_refresh_token_idx'), 'refresh_tokens', ['hashed_refresh_token'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('points >= 0', name=op.f('students_positive_price_check_check')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('students_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('students_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('students_user_id_key'))
    )
    op.create_table('teachers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('teachers_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('teachers_pkey'))
    )
    op.create_table('course_students',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('course_id', sa.UUID(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('course_students_course_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('course_students_student_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('course_students_pkey'))
    )
    op.create_table('groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name=op.f('groups_teacher_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('groups_pkey')),
    sa.UniqueConstraint('name', name=op.f('groups_name_key'))
    )
    op.create_table('group_student',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('group_student_group_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('group_student_student_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'group_id', 'student_id', name=op.f('group_student_pkey')),
    sa.UniqueConstraint('group_id', 'student_id', name='uq_group_student')
    )
    op.create_table('lesson_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=True),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('end_datetime', sa.DateTime(), nullable=False),
    sa.Column('is_opened', sa.Boolean(), nullable=True),
    sa.Column('auditorium', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('lesson_groups_group_id_fkey')),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('lesson_groups_lesson_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('lesson_groups_pkey')),
    sa.UniqueConstraint('lesson_id', 'group_id', name='unique_lesson_group')
    )
    op.create_table('lesson_students',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('lesson_group_id', sa.UUID(), nullable=True),
    sa.Column('is_visited', sa.Boolean(), nullable=True),
    sa.Column('is_excused_absence', sa.Boolean(), nullable=True),
    sa.Column('is_sent_homework', sa.Boolean(), nullable=True),
    sa.Column('is_graded_homework', sa.Boolean(), nullable=True),
    sa.Column('coins_for_visit', sa.Integer(), nullable=True),
    sa.Column('grade_for_visit', sa.Integer(), nullable=True),
    sa.Column('coins_for_homework', sa.Integer(), nullable=True),
    sa.Column('grade_for_homework', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_group_id'], ['lesson_groups.id'], name=op.f('lesson_students_lesson_group_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('lesson_students_student_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('lesson_students_pkey')),
    sa.UniqueConstraint('student_id', 'lesson_group_id', name='unique_student_lesson_group')
    )
    op.create_table('comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('lesson_student_id', sa.UUID(), nullable=True),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_student_id'], ['lesson_students.id'], name=op.f('comments_lesson_student_id_fkey')),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name=op.f('comments_teacher_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('comments_pkey'))
    )
    op.create_table('lesson_student_homework',
    sa.Column('lesson_student_id', sa.UUID(), nullable=False),
    sa.Column('homework_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['homework_id'], ['homeworks.id'], name=op.f('lesson_student_homework_homework_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_student_id'], ['lesson_students.id'], name=op.f('lesson_student_homework_lesson_student_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lesson_student_id', 'homework_id', 'id', name=op.f('lesson_student_homework_pkey'))
    )
    op.drop_constraint("lesson_students_student_id_fkey", "lesson_students", type_="foreignkey")
    
    # Добавляем новый с ON DELETE CASCADE
    op.create_foreign_key(
        "lesson_students_student_id_fkey",  # сохраняем то же имя
        "lesson_students", "students",
        ["student_id"], ["id"],
        ondelete="CASCADE"  # <-- Теперь каскадное удаление на уровне БД
    )

    op.drop_constraint("lesson_groups_group_id_fkey", "lesson_groups", type_="foreignkey")
    
    # Добавляем новый с ON DELETE CASCADE
    op.create_foreign_key(
        "lesson_groups_group_id_fkey",  # сохраняем имя
        "lesson_groups", "groups",
        ["group_id"], ["id"],
        ondelete="CASCADE"  # <--- Теперь удаление группы удалит связанные lesson_groups
    )
    op.drop_constraint("lesson_students_lesson_group_id_fkey", "lesson_students", type_="foreignkey")
    
    # Добавляем новый с ON DELETE CASCADE
    op.create_foreign_key(
        "lesson_students_lesson_group_id_fkey",  # сохраняем имя
        "lesson_students", "lesson_groups",
        ["lesson_group_id"], ["id"],
        ondelete="CASCADE"  # <--- Теперь удаление LessonGroup удалит связанные LessonStudent
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lesson_student_homework')
    op.drop_table('comments')
    op.drop_table('lesson_students')
    op.drop_table('lesson_groups')
    op.drop_table('group_student')
    op.drop_table('groups')
    op.drop_table('course_students')
    op.drop_table('teachers')
    op.drop_table('students')
    op.drop_index(op.f('refresh_tokens_hashed_refresh_token_idx'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('read_status')
    op.drop_table('photo_products')
    op.drop_table('photo_news')
    op.drop_table('photo_courses')
    op.drop_table('password_reset_tokens')
    op.drop_table('notification_recipients')
    op.drop_table('lessons')
    op.drop_table('homeworks')
    op.drop_index(op.f('users_phone_number_idx'), table_name='users')
    op.drop_index(op.f('users_email_idx'), table_name='users')
    op.drop_table('users')
    op.drop_table('products')
    op.drop_table('notifications')
    op.drop_index(op.f('news_name_idx'), table_name='news')
    op.drop_table('news')
    op.drop_table('lesson_html_files')
    op.drop_table('file_homeworks')
    op.drop_table('courses')
    # ### end Alembic commands ###
